package roiderUnion.ids

object ShipsAndWings {
    const val ARGOS = "roider_argos"
    const val TELAMON = "roider_telamon"
    const val TELAMON_FRONT = "roider_telamon_front"
    const val TELAMON_LEFT = "roider_telamon_left"
    const val TELAMON_RIGHT = "roider_telamon_right"
    const val GAMBIT = "roider_gambit"
    const val GAMBIT_ARMOR = "roider_gambit_armor"
    const val RANCH = "roider_ranch"
    const val RANCH_ARMOR = "roider_ranch_armor"
    const val RANCH_DAMPER = "roider_ranch_damper"
    const val RANCH_DAMPER_ARMOR = "roider_ranch_armor_damper"
    const val WRECKER = "roider_wrecker"
    const val WRECKER_ARMOR = "roider_wrecker_armor"
    const val FIRESTORM = "roider_firestorm"
    const val FIRESTORM_LEFT = "roider_firestorm_left"
    const val FIRESTORM_RIGHT = "roider_firestorm_right"
    const val ONAGER = "roider_onager"
    const val ONAGER_ARMOR = "roider_onager_armor"
    const val ONAGER_DAMPER = "roider_onager_damper"
    const val ONAGER_DAMPER_ARMOR = "roider_onager_armor_damper"
    const val AUROCHS = "roider_aurochs"
    const val AUROCHS_ARMOR = "roider_aurochs_armor"
    const val TRAILBOSS = "roider_trailboss"
    const val JANE = "roider_jane"
    const val JANE_ARMOR = "roider_jane_armor"
    const val CALIDOR = "roider_calidor"
    const val ROACH = "roider_roach"
    const val ROACH_ARMOR = "roider_roach_armor"
    const val ROCKROACH = "roider_rockroach"
    const val ROCKROACH_ARMOR = "roider_rockroach_armor"
    const val GARRUCHA_WING = "roider_garrucha_wing"
    const val DESPERADO = "roider_sheriff"
    const val DUSTER_WING = "roider_duster_wing"
    const val HOPSKIP_2_WING = "roider_hopskip2_wing"
    const val GLITZ_WING = "roider_glitz_wing"
    const val ROCKSAW_WING = "roider_rocksaw_wing"
    const val TRACKER_WING = "roider_armature_wing"
    const val TRACKER_SINGLE = "roider_armature_single_wing"
    const val TRACKER_RIGHT = "roider_armature_right"
    const val TRACKER_LEFT = "roider_armature_left"
    const val BREAKER_WING = "roider_breaker_wing"
    const val BORER_WING = "borer_wing"
    const val MINING_DRONE_WING = "mining_drone_wing"

    const val STATION_CORE_1 = "roider_station_core1"
    const val STATION_CORE_2 = "roider_station_core2"
    const val STATION_CORE_3 = "roider_station_core3"
    const val STATION_DRONE = "roider_station_drone"
    const val STATION_DRONE_HIDDEN = "roider_station_drone_hidden"
}